### PR TITLE
build: agent-js peer dependency v2

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

If we bump agent-js in ic-js in our dapps, we also need to bump it in the verifiable-credentials.

### CODE REVIEW

**Review by frederikrothenberger — APPROVED** [review]
Thanks

**Comment by peterpeterparker** [comment]
@lmuntaner agent-js v2.0.0 has been merged in ic-js main

**Comment by peterpeterparker** [comment]
I merge this as I need a next version in Oisy Wallet.

**Comment by lmuntaner** [comment]
@peterpeterparker did you do a new release of the js-library already?

**Comment by peterpeterparker** [comment]
`ic-js@next` yes. I was considering whether we should propose a release of the dApps first before releasing ic-js, but I can also prepare the release of ic-js now. What do you prefer?

**Comment by lmuntaner** [comment]
I meant the npm library "@dfinity/verifiable-credentials". Don't you say you need it?

**Comment by peterpeterparker** [comment]
Ah! Yes also `next` version only. Did so yesterday: https://github.com/dfinity/verifiable-credentials-sdk/actions/runs/10563242261

**Pull request merged**
