### PR TITLE
build: agent-js peer dependency v2

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

If we bump agent-js in ic-js in our dapps, we also need to bump it in the `verifiable-credentials`.

### CODE REVIEW

**Review by lmuntaner — APPROVED** [review]
Thanks!

**Comment by peterpeterparker** [comment]
Forgot I already provided this PR.

ic-js is still on v1.4.0. NNS dapp should update the test suite to unlock the migration in our eco-system. We should maybe wait on it before merging this.

**Comment by lmuntaner** [comment]
> Forgot I already provided this PR.
> 
> ic-js is still on v1.4.0. NNS dapp should update the test suite to unlock the migration in our eco-system. We should maybe wait on it before merging this.

NNS Dapp doesn't use this library (yet). Do they have a timeline when they will be on version 2?

**Comment by peterpeterparker** [comment]
No timeline but, I'll need agent-js v2 for the signer standard so I monitor the topic closely.

**Pull request closed without merging**
